
import json
from datetime import datetime
import io

def create_txt_report(summary, questions, faqs, chunks, chat_history):
    """Create text document"""
    document = "=" * 80 + "\n"
    document += " " * 25 + "COMPREHENSIVE BOOK ANALYSIS\n"
    document += "=" * 80 + "\n\n"
    
    document += "EXECUTIVE SUMMARY\n" + "=" * 25 + "\n\n"
    document += f"{summary}\n\n"
    
    document += "IMPORTANT QUESTIONS\n" + "=" * 25 + "\n\n"
    if questions:
        for i, question in enumerate(questions, 1):
            document += f"{i:02d}. {question}\n"
    document += "\n"
    
    document += "FREQUENTLY ASKED QUESTIONS\n" + "=" * 35 + "\n\n"
    if faqs:
        for i, (q, a) in enumerate(faqs, 1):
            document += f"Q{i:02d}: {q}\n"
            document += f"A{i:02d}: {a}\n\n"
    
    if chat_history:
        document += "CHAT HISTORY\n" + "=" * 20 + "\n\n"
        for i, (q, a) in enumerate(chat_history, 1):
            document += f"You: {q}\n"
            document += f"AI: {a}\n\n"
    
    document += "\n" + "=" * 80 + "\n"
    document += f"Generated on: {datetime.now().strftime('%Y-%m-%d at %H:%M:%S')}\n"
    document += f"Content Sections Analyzed: {len(chunks)}\n"
    document += "=" * 80
    
    return document.encode('utf-8')

def create_json_report(summary, questions, faqs, chunks, chat_history):
    """Create JSON document"""
    report_data = {
        "metadata": {
            "generated_date": datetime.now().isoformat(),
            "content_sections": len(chunks),
            "analysis_type": "Comprehensive"
        },
        "summary": summary,
        "questions": questions,
        "faqs": [{"question": q, "answer": a} for q, a in faqs],
        "chat_history": [{"question": q, "answer": a} for q, a in chat_history]
    }
    return json.dumps(report_data, indent=2, ensure_ascii=False).encode('utf-8')

def create_html_report(summary, questions, faqs, chunks, chat_history):
    """Create HTML document"""
    html_content = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <title>Book Analysis Report</title>
        <style>
            body {{ font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin: 40px; line-height: 1.6; color: #333; }}
            .header {{ text-align: center; background: linear-gradient(135deg, #2c3e50, #3498db); color: white; padding: 40px; border-radius: 12px; margin-bottom: 30px; box-shadow: 0 4px 15px rgba(0,0,0,0.1); }}
            .section {{ margin: 30px 0; padding: 25px; border-left: 5px solid #3498db; background: #f8f9fa; border-radius: 8px; }}
            h1 {{ margin: 0; font-weight: 300; letter-spacing: 1px; }}
            h2 {{ color: #2c3e50; margin-top: 0; }}
            .p-meta {{ color: rgba(255,255,255,0.8); font-size: 0.9rem; }}
            .question-item {{ font-weight: 600; color: #2c3e50; margin-bottom: 8px; }}
            .faq-item {{ margin-bottom: 20px; }}
            .faq-q {{ font-weight: bold; color: #d35400; }}
            .faq-a {{ margin-top: 5px; color: #555; }}
            .chat-user {{ background: #e3f2fd; padding: 12px; margin: 8px 0 8px 40px; border-radius: 12px 12px 2px 12px; }}
            .chat-ai {{ background: #f5f5f5; padding: 12px; margin: 8px 40px 8px 0; border-radius: 12px 12px 12px 2px; border-left: 4px solid #16a085; }}
        </style>
    </head>
    <body>
        <div class="header">
            <h1>Comprehensive Book Analysis</h1>
            <p class="p-meta">Generated on {datetime.now().strftime('%Y-%m-%d at %H:%M:%S')}</p>
        </div>
        
        <div class="section">
            <h2>Executive Summary</h2>
            <div style="white-space: pre-wrap;">{summary}</div>
        </div>
        
        <div class="section">
            <h2>Key Questions</h2>
            <ol>
    """
    
    if questions:
        for question in questions:
            html_content += f'<li class="question-item">{question}</li>'
    
    html_content += """
            </ol>
        </div>
        
        <div class="section">
            <h2>Frequently Asked Questions</h2>
    """
    
    if faqs:
        for q, a in faqs:
            html_content += f'<div class="faq-item"><div class="faq-q">{q}</div><div class="faq-a">{a}</div></div>'
    
    if chat_history:
        html_content += """
        </div>
        <div class="section">
            <h2>Chat History</h2>
        """
        for q, a in chat_history:
            html_content += f'<div class="chat-user"><strong>You:</strong> {q}</div>'
            html_content += f'<div class="chat-ai"><strong>AI:</strong> {a}</div>'
    
    html_content += """
        </div>
        <div style="text-align: center; margin-top: 50px; color: #aaa; font-size: 0.8rem;">
            Generated by AI Book Analyzer Pro
        </div>
    </body>
    </html>
    """
    return html_content.encode('utf-8')
